### ISSUE TITLE
Internal error when i try to save a wiki page

### ISSUE THREAD

**Issue by ZerooCool** [patope/redmine-hangouts-chat#3]
Note that if I refresh the page, by clicking on the wiki link, the page has been updated.
If I use the save button, I have the following error :

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.If you are the Redmine administrator, check your log files for details about the error.Back

App 11590 output: plugins/redmine_hangouts_chat/lib/redmine_hangouts_chat/listener.rb:229:in `speak'
App 11590 output: plugins/redmine_hangouts_chat/lib/redmine_hangouts_chat/listener.rb:196:in `controller_wiki_edit_after_save'
App 11590 output: lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
App 11590 output: lib/redmine/hook.rb:61:in `each'
App 11590 output: lib/redmine/hook.rb:61:in `block in call_hook'
App 11590 output: lib/redmine/hook.rb:58:in `tap'
App 11590 output: lib/redmine/hook.rb:58:in `call_hook'
App 11590 output: lib/redmine/hook.rb:91:in `call_hook'
App 11590 output: app/controllers/wiki_controller.rb:179:in `update'
App 11590 output: lib/redmine/sudo_mode.rb:63:in `sudo_mode'
App 11590 output: Started PUT "/projects/mise-en-place-d-une-coordination-interne/wiki/Wiki" for 127.0.0.1 at 2019-04-08 23:17:17 +0200
App 11590 output: Processing by WikiController#update as HTML
App 11590 output:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"jfAIOEbRwjkHxFIiJ91+PI3k5wbZspSEVD2tYlfbJsxmoPfhcR9fZ1F4R3pdUDQ4WK5X8jZKSq15H0GyT3dC5g==", "content"=>{"version"=>"1", "$
App 11590 output:   Current user: Zer00CooL (id=1)
App 11590 output: Completed 500 Internal Server Error in 27ms (ActiveRecord: 12.0ms)

**Comment by ZerooCool** [comment]
I unchecked the choice to warn about editing a wiki page or issue.
I switched to no choice to display the observers.

I no longer have the error message on the wiki. :( .... :/ .... :)

However, I do not get anything on slack, whether the options are enabled or not. I use here a virtual machine under Mint Tara to test the plugin on Redmine 4.0.2 stable
